sudo : required
services : 
  - docker
before_install : 
  - docker build -t oussamaelleuch1995/docker-react -f Dockerfile.dev .
script : 
  - docker run oussamaelleuch1995/docker-react npm run test -- --coverage
